### PR TITLE
Fix macOS builds

### PR DESCRIPTION
**Pull request by JeremyRand**
This PR fixes the build errors for the `release-osx-x86_64` target.

### CODE REVIEW

**Comment by JeremyRand** [comment]
If anyone wants to test the resulting binaries without building from source, here's a binary I just built:

http://zs7xwvcspvnnrqhvyxyxpjkihc4lva3yustfr75j6giy24mdfg3rcwqd.onion/#DW9QDpGmdLLwQAw9f4MmZQ

SHA256 hash is `ec79f6ce5eaaad0f84a3b116e93ed22b0bc93b61abc73a9e70a501d37880a11c`.

**Comment by JeremyRand** [comment]
For anyone who wants to test the binaries with both this PR and https://github.com/namecoin/ncdns-repro/pull/26 applied, here's a binary:

http://zs7xwvcspvnnrqhvyxyxpjkihc4lva3yustfr75j6giy24mdfg3rcwqd.onion/#gtITR1ys2EJ6hFAQUfgLFw

SHA256 hash is `6a4d4ffe0d8dafa69fdc9815933f6f1856eaacc732bcaac2b45d25c2e83c926a`.

**Comment by JeremyRand** [comment]
@hlandau This PR (as well as #26 and #27 ) will be merged in 1 week if I don't hear anything from you on the subject.

**Comment by cojapacze** [comment]
> http://zs7xwvcspvnnrqhvyxyxpjkihc4lva3yustfr75j6giy24mdfg3rcwqd.onion/#gtITR1ys2EJ6hFAQUfgLFw
> 
> SHA256 hash is `6a4d4ffe0d8dafa69fdc9815933f6f1856eaacc732bcaac2b45d25c2e83c926a`.

Tested on macOS Mojave 10.14.5 with success.

**Pull request merged**
